#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t liquid"

$L " __    __  __   _  _  __  ____  ____  _  _   __    __  ____  _  _ ";
$L "(  )  (  )/  \ / )( \(  )(    \/ ___)( \/ ) /  \  /  \(_  _)/ )( \";
$L "/ (_/\ )((  O )) \/ ( )(  ) D (\___ \/ \/ \(  O )(  O ) )(  ) __ (";
$L "\____/(__)\__\)\____/(__)(____/(____/\_)(_/ \__/  \__/ (__) \_)(_/"
$L "Welcome to Android `getprop ro.build.version.release` / LiquidSmooth-`getprop ro.liquid.version`";
